name: Build & Deploy
on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Build
        run: |
          yarn
          yarn build

      - name: Check Cloudflare API Token
        id: check_token
        run: |
          if [[ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]]; then
            echo "Cloudflare API token is not set. Skipping deployment."
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi
        shell: bash

      # - name: Copy files excluding .gitignore
      #   if: steps.check_token.outputs.skip != 'true'
      #   run: |
      #     mkdir preserved
      #     rsync -av --progress . preserved --exclude-from='.gitignore'

      # - name: Upload preserved directory
      #   if: steps.check_token.outputs.skip != 'true'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifacts
      #     path: preserved

      - name: Deploy to Cloudflare
        if: steps.check_token.outputs.skip != 'true'
        uses: ubiquity/cloudflare-deploy-action@main
        with:
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          repository: ${{ github.repository }}
          production_branch: ${{ github.event.repository.default_branch }}
          output_directory: "dist"
          current_branch: ${{ github.ref_name }}
        # env:
        # Add any environment variables you need to pass along here
        #   SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        #   SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
