name: Empty String Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-for-empty-strings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          yarn install
      - name: Check for Empty Strings
        run: |
          yarn tsx .github/empty-string-checker.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}