name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          default-branch: main
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
          registry-url: https://registry.npmjs.org/
      - run: |
          yarn install --immutable --immutable-cache --check-cache
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
